### ISSUE TITLE
Problems with generated model tests

### ISSUE THREAD

**Issue by innerdvations** [biggora/caminte-cli#2]
I'm using a mongodb schema.

When I create models with the command  `caminte -t -m User name:String pass:String email:String` and then run the tests, all the assertions `found.id.should.equal(id);` fail because found.id and id appear to be objects.  If I change the assertions to a deep equals like `found.id.should.eql(id)` they work.

Also, the tests for #find fail unless the test database is manually cleared after every run, because it finds the old records.  I'm not sure if that's intended, but it may be nicer to destroyAll before each model test or at least take that into account in the #find test.

**Comment by biggora** [comment]
Thanks, I fixed it.
